totem {
    version: 2
    cluster_name: nvme_cluster
    transport: knet
    crypto_cipher: aes256
    crypto_hash: sha256
    cluster_uuid: 83ee97171a5b483ea717f0746289de43
}

nodelist {
    node {
        ring0_addr: 192.168.177.11
        name: 192.168.177.11
        nodeid: 1
    }

    node {
        ring0_addr: 192.168.177.12
        name: 192.168.177.12
        nodeid: 2
    }
}

quorum {
    provider: corosync_votequorum
    two_node: 1
    wait_for_all: 1
}

logging {
    to_logfile: yes
    logfile: /var/log/corosync/corosync.log
    to_syslog: yes
    timestamp: on
}
