[Controllers]
# Maintain a persistent connection to Node 1's RAID0 export
controller=transport=rdma;traddr=192.168.177.11;trsvcid=4420;nqn=nqn.2026-03.dgx:node1-shared
# Maintain a persistent connection to mini (TrueNAS) NVMe-oF TCP export
controller=transport=tcp;traddr=10.1.1.2;trsvcid=4420;nqn=nqn.2011-06.com.truenas:uuid:df582e73-2848-46f6-8dc3-1aa32b42d26d:mini;host-traddr=10.1.1.3
